backend/board/urls.py
from django.urls import path

from . import views

app_name = 'board'

urlpatterns = [
    # ex: /board/
    path('', views.index, name='index'),
    # ex: /board/5/
    path('<int:post_id>/', views.detail, name='detail'),
    # Vue API
    path('api/posts/<int:post_id>/', views.post_api_detail, name='post_api_detail'),
    path('api/posts/', views.post_api_index, name='post_api_index'),
    # ex: /board/create/
    path('create/', views.create, name='create'),
    # ex: /board/update/5/
    path('update/<int:post_id>/', views.update, name='update'),
    # ex: /board/delete/5/
    path('delete/<int:post_id>/', views.delete, name='delete'),
    # ex: /board/about/
    path('about/', views.about, name='about'),
]

backend/mypage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

backend/board/models.py
from django.db import models

class Post(models.Model):
    CATEGORY_CHOICES = [
        ('free', '자유'),
        ('diary', '일기'),
        ('activity', '활동'),
        ('2d', '2D'),
        ('3d', '3D'),
        ('android-permission', '앱 권한'),
        ('chatbot', '챗봇'),
        ('classification', '분류'),
        ('flea-market', 'Flea Market'),
        ('green-code', 'Green Code'),
    ]
    
    category = models.CharField(
        max_length=20,
        choices=CATEGORY_CHOICES,
        default='free'
    )
    tag = models.CharField(
        max_length=20,
        default='tag1'
    )
    title = models.CharField(max_length=200)
    content = models.TextField()
    post_date = models.DateTimeField("date posted")
    update_date = models.DateTimeField("date updated", auto_now=True) # 저장될 때마다 매번 갱신
    
    def __str__(self):
        return self.title

backend/board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.utils import timezone
from datetime import datetime

from .models import Post

CATEGORY_TAGS = {
    '2d': ['프로젝트', '개발일지', '시연'],
    '3d': ['프로젝트', '개발일지', '시연'],
    'android-permission': ['Test1', 'Test2', 'Test3'],
    'chatbot': ['Test1', 'Test2', 'Test3'],
    'classification': ['Test1', 'Test2', 'Test3'],
    'flea-market': ['Test1', 'Test2', 'Test3'],
    'green-code': ['Test1', 'Test2', 'Test3'],
}

def index(request):
    category = request.GET.get('category')
    tag = request.GET.get('tag')
    
    parentCategory = get_parent_category(category)
    tag_list = CATEGORY_TAGS.get(category, [])
    
    latest_post_list = Post.objects.all().order_by('-post_date')
    if category:
        latest_post_list = latest_post_list.filter(category=category).order_by('-post_date')
    if tag:
        latest_post_list = latest_post_list.filter(tag=tag).order_by('-post_date')
        
    paginator = Paginator(latest_post_list, 10) # 10 posts per one page
    
    page_number = request.GET.get('page') # current page
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'selected_category': category,
        'parent_category': parentCategory,
        'tag_list': tag_list,
    }
    
    if request.headers.get('x-requested-with') == 'XMLHttpRequest': # AJAX 요청인 경우
        return render(request, 'board/post_list_partial.html', context)
    else:
        return render(request, 'board/index.html', context)
    
def get_parent_category(category):
    mapping = {
        "2d": "Unity",
        "3d": "Unity",
        "android-permission": "AI",
        "chatbot": "AI",
        "classification": "AI",
        "flea-market": "Full Stack",
        "green-code": "Full Stack",
    }
    return mapping.get(category, "Unknown")

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'board/detail_vue.html', {'post': post})

# Vue
def post_api_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    return JsonResponse({
        'id': post.id,
        'title': post.title,
        'content': post.content,
        'post_date': post.post_date.isoformat()
    })
    
def post_api_index(request):
    category = request.GET.get('category')
    #tag = request.GET.get('tag')
    
    #parentCategory = get_parent_category(category)
    #tag_list = CATEGORY_TAGS.get(category, [])
    
    latest_post_list = Post.objects.all().order_by('-post_date')
    if category:
        latest_post_list = latest_post_list.filter(category=category).order_by('-post_date')
    #if tag:
    #    latest_post_list = latest_post_list.filter(tag=tag).order_by('-post_date')
        
    #paginator = Paginator(latest_post_list, 10) # 10 posts per one page
    
    #page_number = request.GET.get('page') # current page
    #page_obj = paginator.get_page(page_number)
    
    post_data = [
        {
            'id': post.id,
            'title': post.title,
            'category': post.category,
            'content': post.content,
            'post_date': post.post_date.strftime('%Y-%m-%d'),
        }
        for post in latest_post_list
    ]
    
    return JsonResponse({'posts': post_data})

@csrf_exempt
def create(request):
    if request.method == 'GET':
        return render(request, "board/create.html")
    elif request.method == 'POST':
        # request.POST[] : key가 없으면 예외(MultiValueDictKeyError) 발생
        category = request.POST['category']
        tag = request.POST['tag']
        title = request.POST['title']
        content = request.POST['content']
        
        # request.POST.get() : key가 없으면 None 반환
        is_checked = request.POST.get('rand_date')
        selected_date = request.POST.get('selected_date')
        
        print(is_checked)
        if is_checked and selected_date:
            try:
                post_date = datetime.strptime(selected_date, '%Y-%m-%d')
                print(post_date)
            except ValueError:
                post_date = timezone.now()
        else:
            post_date = timezone.now()
        
        newPost = Post(
            category=category,
            tag=tag,
            title=title,
            content=content,
            post_date=post_date
        )
        newPost.save()
        url = '/board/' + str(newPost.id)
        return redirect(url)
    
@csrf_exempt
def update(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'GET':
        return render(request, "board/update.html", {'post': post})
    elif request.method == 'POST':
        category = request.POST['category']
        title = request.POST['title']
        content = request.POST['content']
        
        is_checked = request.POST.get('rand_date')
        selected_date = request.POST.get('selected_date')
        
        if is_checked and selected_date:
            try:
                post_date = datetime.strptime(selected_date, '%Y-%m-%d')
            except ValueError:
                post_date = timezone.now()
        else:
            post_date = post.post_date
        
        post.category = category
        post.title = title
        post.content = content
        post.post_date = post_date
        post.save()
        return render(request, 'board/detail.html', {'post': post})
    
@csrf_exempt
def delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    if request.method == 'POST':
        post.delete()
        return redirect('/board/')
    else:
        return render(request, 'board/detail.html', {
            'post': post,
            'error_message': '삭제는 POST 요청으로만 가능합니다'
        })
        
def about(request):
    return render(request, 'board/about.html')

backend/board/templates/board/about.html
{% extends 'base.html' %}

{% block title %}About Me{% endblock %}

{% block content %}
<div class="resume-container">
  <section class="header">
    <h1>홍길동</h1>
    <p>소프트웨어 개발자</p>
    {% comment %} <p>Backend Developer | Security Enthusiast | CS Major</p> {% endcomment %}
  </section>

  <section class="contact">
    <h3>Contact</h3>
    <p>010-1234-5678</p>
    <p>jtm4902@naver.com</p>
    <p><a href="https://github.com/Melted-Choco">github</a></p>
  </section>

  <section class="profile">
    <h2>Profile</h2>
    <p>
      효율적인 코드를 선호하고 정보 보안에 많은 관심을 가진 신입 소프트웨어 개발자입니다.
      다양한 시도를 두려워하지 않으며 시스템 개선을 위해 지속적으로 고민합니다.
      프로젝트를 수행함에 있어 적극적으로 참여하고 원활한 소통을 위해 꾸준히 노력하는 개발자가 되고자 합니다.
    </p>
  </section>

  <section class="skills">
    <h2>Skills</h2>
    <ul>
      <li>Python, Django, JavaScript, C#</li>
      <li>Unity, MySQL, Git, REST API</li>
      <li>System Security (self-studied)</li>
    </ul>
  </section>

  <section class="education">
    <h2>Education</h2>
    <p>성균관대학교 소프트웨어학과</p>
    <p>2019.03 ~ 2025.02 수료</p>
    <p>학점 4.05 / 4.5</p>
    <p>ps. 인턴 미경험</p>
  </section>

  <section class="certificate">
    <h2>Certificate</h2>
    <p>컴퓨터활용능력 1급</p>
  </section>
</div>
{% endblock %}

{% block extra_css %}
<style>
  .resume-container {
    max-width: 800px;
    margin: 40px auto;
    padding: 40px;
    background-color: #ffffff;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
    font-family: 'Segoe UI', sans-serif;
    line-height: 1.6;
    color: #333;
  }

  .resume-container h1 {
    font-size: 2.5rem;
    margin-bottom: 5px;
    text-align: center;
  }

  .resume-container p {
    text-align: center;
    margin-bottom: 20px;
  }

  section {
    margin-top: 30px;
  }

  section h2 {
    font-size: 1.5rem;
    border-bottom: 2px solid #eee;
    padding-bottom: 5px;
    margin-bottom: 10px;
    color: #444;
  }

  ul {
    padding-left: 20px;
  }

  li {
    margin-bottom: 10px;
  }

  @media (max-width: 768px) {
    .resume-container {
      padding: 20px;
    }

    .resume-container h1 {
      font-size: 2rem;
    }

    section h2 {
      font-size: 1.2rem;
    }
  }
</style>
{% endblock %}

backend/board/templates/board/create.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}
<h1>Create Post</h1>

<form action="/board/create/" method="post">
    <div id="create-group">
        <select name="category" id="create-category" required="required">
            <option value="" selected disabled hidden>카테고리</option>
            <option value="free">자유</option>
            <option value="diary">일기</option>
            <option value="activity">활동</option>
            <!-- Unity -->
            <option value="2d">2D</option>
            <option value="3d">3D</option>
            <!-- AI -->
            <option value="android-permission">앱 권한</option>
            <option value="chatbot">챗봇</option>
            <option value="classification">분류</option>
            <!-- Full Stack -->
            <option value="flea-market">Flea Market</option>
            <option value="green-code">Green Code</option>
        </select>
        <select name="tag" id="create-tag" required="required" style="width: 10%; min-width: 60px; max-width: 80px;">
            <option value="" selected disabled hidden>태그</option>
        </select>
        <input type="text" name="title" placeholder="Title" id="create-title" required>
        <div id="create-group-date">
            <input type="checkbox" name="rand_date" value="on" id="create-date" style="display: none;"> 
            <label for="create-date" style="color: #3498db;">날짜 설정</label>
            <br>
            <input type="date" name="selected_date" id="selected-date">
        </div>
    </div>
    <div id="toolbar">
        <!-- 헤더 & 크기 -->
        <select class="ql-header">
            <option selected></option>
            <option value="1">H1</option>
            <option value="2">H2</option>
            <option value="3">H3</option>
        </select>
        <select class="ql-size">
            <option value="10px">10</option>
            <option value="12px">12</option>
            <option selected value="16px">16</option>
            <option value="20px">20</option>
            <option value="32px">32</option>
            <option value="48px">48</option>
        </select>

        <!-- 폰트 -->
        <select class="ql-font">
            <option selected></option>
            <option value="serif">Serif</option>
            <option value="monospace">Monospace</option>
        </select>

        <!-- 색상 -->
        <select class="ql-color"></select>

        <!-- 정렬 -->
        <select class="ql-align">
            <option selected></option>
            <option value="center"></option>
            <option value="right"></option>
            <option value="justify"></option>
        </select>

        <!-- 서식 -->
        <button class="ql-bold"></button>
        <button class="ql-italic"></button>
        <button class="ql-underline"></button>
        <button class="ql-link"></button>
        <button class="ql-image"></button>
    </div>
    <div id="editor-container" style="height: 300px;"></div>
    <textarea name="content" id="create-content" style="display: none;"></textarea>
    <div><input type="submit" class="button-submit"></div>
</form>

<p><a href="/board/">Cancel</a></p>
{% endblock %}

backend/board/templates/board/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<article style="max-width: 800px; margin: auto; padding: 24px; border: 1px solid #ddd; border-radius: 12px; background-color: #fdfdfd; box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05)">

    <div id="category-label">
        {{ post.get_category_display }}
    </div>
    <div style="display: flex; justify-content: space-between; align-items: center;">
    <h1 style="margin: 0 0 16px 0;">{{ post.title }}</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <p style="color: #888; margin-bottom: 20px; text-align: right; font-size: 0.8em;">
        작성일: {{ post.post_date|date:"Y.m.d" }}
    </p>
    </div>

    <div style="line-height: 1.0; font-size: 1rem; padding: 10px 0; border-top: 1px solid #ddd; border-bottom: 1px solid #ddd;">
        {% autoescape off %}
        {{ post.content }}
        {% endautoescape %}
    </div>

    <div style="margin-top: 24px;">
        <a href="{% url "board:update" post.id %}" style="margin-right: 12px; color: #3498db;">Update the Post</a>
        <a href="/board/" style="margin-right: 12px; color: #888;">Back to List</a>
        
        <form action="{% url 'board:delete' post.id %}" method="post" style="display: inline;">
            <button type="submit" onclick="return confirm('정말 삭제하시겠습니까?')" id="button-delete">Delete the Post</button>
        </form>
    </div>

</article>
{% endblock %}

backend/board/templates/board/detail_vue.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post Detail (Vue){% endblock %}

{% block content %}
<div id="post-app" style="max-width: 800px; margin: auto;"></div>

<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
<script src="{% static 'js/post_detail_vue.js' %}"></script>
<script>
    window.addEventListener('DOMContentLoaded', function() {
        const postId = {{ post.id }};
        loadPostApp(postId); // post_detail_vue.js에 있는 loadPostApp 호출
    });
</script>
{% endblock  %}

backend/board/templates/board/index.html
{% extends 'base.html' %}

{% block title %}Post List{% endblock %}

{% block content %}
<div id="category-title">
    <span style="font-size: 1.3rem; font-weight: bold; color: #555;">{{ parent_category }}</span>
    <span style="font-size: 1.3rem; color: #aaa;"> &gt; </span>
    <span style="font-size: 1.3rem; font-weight: bold; color: #222;">{{ selected_category|title }}</span>
</div>

{% if tag_list %}
    <div id="tag-bar">
        {% for tag in tag_list %}
            <button class="button-tag" data-tag="{{ tag }}">{{ tag }}</button>
        {% endfor %}
        {% comment %} <button class="button-tag" data-tag="tag2">Tag2</button>
        <button class="button-tag" data-tag="tag3">Tag3</button> {% endcomment %}
    </div>
{% endif %}

{% if page_obj %}
    <ul class="post-list">
        {% for post in page_obj %}
            <li>
                <div class="post-number">{{ post.id }}</div>
                <a href="{% url 'board:detail' post.id %}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>

    <!-- Paging Link -->
    <div class="pagination">
        <div class="pagination-prev">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">Prev</a>
            {% else %}
                <span class="invisible">Prev</span>
            {% endif %}
        </div>

        <div class="pagination-center">
            <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        </div>

        <div class="pagination-next">
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">Next</a>
            {% else %}
                <span class="invisible">Next</span>
            {% endif %}
        </div>
    </div>
{% else %}
    <p>No post are available.</p>
{% endif %}

<a href="/board/create/">Create New Post</a>
{% endblock %}

backend/board/templates/board/post_list_partial.html
{% for post in page_obj %}
<li>
    <div class="post-number">{{ post.id }}</div>
    <a href="{% url 'board:detail' post.id %}">{{ post.title }}</a>
</li>
{% empty %}
<li>No posts found.</li>
{% endfor %}

backend/board/templates/board/update.html
{% extends 'base.html' %}

{% block title %}Update Post{% endblock %}

{% block content %}
<h1>Update Post</h1>

<form action="/board/update/{{ post.id }}/" method="post">
    <div id="create-group">
        <!-- 카테고리 -->
        <select name="category" id="create-category" required>
            <option value="" disabled hidden>카테고리</option>
            <option value="free" {% if post.category == 'free' %}selected{% endif %}>자유</option>
            <option value="diary" {% if post.category == 'diary' %}selected{% endif %}>일기</option>
            <option value="activity" {% if post.category == 'activity' %}selected{% endif %}>활동</option>
            <!-- Unity -->
            <option value="2d" {% if post.category == '2d' %}selected{% endif %}>2D</option>
            <option value="3d" {% if post.category == '3d' %}selected{% endif %}>3D</option>
            <!-- AI -->
            <option value="android-permission" {% if post.category == 'android-permission' %}selected{% endif %}>Android Permission</option>
            <option value="chatbot" {% if post.category == 'chatbot' %}selected{% endif %}>Chatbot</option>
            <option value="classification" {% if post.category == 'classification' %}selected{% endif %}>Classification</option>
            <!-- Full Stack -->
            <option value="flea-market" {% if post.category == 'flea-market' %}selected{% endif %}>Flea Market</option>
            <option value="green-code" {% if post.category == 'green-code' %}selected{% endif %}>Green Code</option>
        </select>
        <!-- 제목 -->
        <input type="text" name="title" placeholder="Title" id="create-title" value="{{ post.title }}" required>
        <!-- 날짜 -->
        <div id="create-group-date">
            <input type="checkbox" name="rand_date" value="on" id="create-date" style="display: none;"> 
            <label for="create-date" style="color: #3498db;">날짜 설정</label>
            <br>
            <input type="date" name="selected_date" id="selected-date">
        </div>
    </div>
    <div id="toolbar">
        <!-- 헤더 & 크기 -->
        <select class="ql-header">
            <option selected></option>
            <option value="1">H1</option>
            <option value="2">H2</option>
            <option value="3">H3</option>
        </select>
        <select class="ql-size">
            <option value="10px">10</option>
            <option value="12px">12</option>
            <option selected value="16px">16</option>
            <option value="20px">20</option>
            <option value="32px">32</option>
            <option value="48px">48</option>
        </select>

        <!-- 폰트 -->
        <select class="ql-font">
            <option selected></option>
            <option value="serif">Serif</option>
            <option value="monospace">Monospace</option>
        </select>

        <!-- 색상 -->
        <select class="ql-color"></select>

        <!-- 정렬 -->
        <select class="ql-align">
            <option selected></option>
            <option value="center"></option>
            <option value="right"></option>
            <option value="justify"></option>
        </select>

        <!-- 서식 -->
        <button class="ql-bold"></button>
        <button class="ql-italic"></button>
        <button class="ql-underline"></button>
        <button class="ql-link"></button>
    </div>
    <div id="editor-container" style="height: 300px;"></div>
    <textarea name="content" id="create-content" style="display: none;">{{ post.content|safe}}</textarea>
    <div><input type="submit" class="button-submit"></div>
</form>

<p><a href="/board/">Cancel</a></p>
{% endblock %}